### ISSUE TITLE
classes/XeroInvoiceCreate not available 

### ISSUE THREAD

**Issue by pradykris** [benedwards44/Apex-for-Xero#1]
classes/XeroInvoiceCreate is not available on the Git and classes/XeroInvoice.cls(XeroInvoice) does not have a meta file.

I tried to deploy the git directly into my salesforce org using http://andyinthecloud.com/2013/09/24/deploy-direct-from-github-to-salesforce/

and ran into these errors

**Comment by benedwards44** [comment]
@pradykris looks like I was missing some metadata and had mis-named a class. I've pushed a latest fix to master, so should be ok now.

Try again and let me know.

**Comment by pradykris** [comment]
@benedwards44  it works fine now :)
Thanks for making the change and sharing this. Will keep you posted if i run into some other issues
