### ISSUE TITLE
Xero OAuth 1 Endpoint Depreciated

### ISSUE THREAD

**Issue by user851** [benedwards44/Apex-for-Xero#19]
Hi Ben,

Thanks for the effort that you have put into this project, it has been very useful.

With Xero depreciating Oauth 1 as of earlier this month no new private apps can be created. I am wondering if you have plans to update this repo to support Oauth2?

Regards

Daniel

**Comment by user851** [comment]
Done!

**Comment by adam-jones-net** [comment]
@benedwards44 , can I just confirm, what is the process exactly in terms of going from Oauth 1 to Oauth 2 in terms of existing code inside of SalesForce?   

I have an app that I have to light touch maintain that I didn't write inside of SF and it's still on an Oauth 1 setup.   Do I just follow your Oauth 2 setup instructions and the existing apex code inside of SF will just work as before (ie all your functions and interfaces are the same)?  Or is it more complex than that with code changes being likely required inside of SF?
