### ISSUE TITLE
Cannot deploy to Production

### ISSUE THREAD

**Issue by lknlookin** [benedwards44/Apex-for-Xero#3]
Hi Ben,

Thank for your great code. It can deploy to Sandbox but if deploy to Production it shows error as below.

> Deployment CompleteTest failure, method: ChatterAnswersAuthProviderRegTest.validateCreateUpdateUser -- System.DmlException: Insert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [ProfileId]: [ProfileId] stack Class.ChatterAnswersAuthProviderRegTest.validateCreateUpdateUser: line 31, column 1
> 
> Code coverage issue -- Average test coverage across all Apex Classes and Triggers is 63%, at least 75% test coverage is required.

Could you please fix or guide to make deploy happen?

Regards,
In

**Comment by benedwards44** [comment]
@lknlookin This error has nothing to do with these components, looks like an error with your ```ChatterAnswersAuthProviderRegTest``` class, which is not a component in this repository.
