### ISSUE TITLE
Deployment Failures

### ISSUE THREAD

**Issue by faceroy** [benedwards44/Apex-for-Xero#4]
Hi Ben,

When deploying to a dev org I receive the following Failures:
classes/XeroCalloutResponseParser.cls(32,74):Invalid type: XeroInvoice
classes/XeroAccountingApiTest.cls(131,8):Invalid type: XeroInvoice
classes/XeroAccountingApi.cls(96,51):Invalid type: XeroInvoice
classes/XeroInvoice.cls(22,16):Identifier name is reserved: Date

Any ideas?

Many thanks

**Comment by benedwards44** [comment]
@faceroy sorry just saw this issue. I've fixed this now.
